### PR TITLE
Add feature: Write Name text component

### PR DESCRIPTION
**Pull request by thgiang-coder**
Hi Hasin,
Thanks for waiting, this is a bit difficult for me, because I am not yet proficient in Reactjs. I have added a Text Component to the project following the instructions in the CONTRIBUTED.md file. This Text Component is called writeName-text(Write Name), which allows users to write their name. I also added an animation effect to make it look nice.
I hope you like it, and if there are any mistakes, I would love to receive your feedback.
I hope your project will develop more and more.
Best regards.

### CODE REVIEW

**Review by hasin-zaman — CHANGES_REQUESTED** [review]
@Giang0402 Great job! There are only a few things that you need to take into consideration. 

1. Always remember to use consistent naming conventions in the project. See the Route path you have defined its "/Text/.." while the example Route you may find is "/buttons/.." this means you should define route following the existing convention as "/texts/.."
2. Always keep your code as readable as possible. Unused commented out code adds to unreadability. So in your Page file you should delete the commented code as well as unused imports.
3. When it comes to reusability, think of how your component can be reused in generic scenarios instead of specific ones. In your case you have named your component WriteName which suggests you can use it where writing names only. Can you think of a better more generic name? Let's say AnimatedText for example. Now the same component suggests that it can be used to write names as well as any form of text like titles, section headers etcetera. 

Rest of the work looks good. Also, I'd really appreciate if you can share a screenshot as well. Thanks.

**Comment by thgiang-coder** [comment]
Hi **@hasin-zaman** ,
Thanks for your feedback. I have made some changes as suggested. 
This includes: 
- Changing the Component name to Animated Text
- Changing the Route to texts/animated-text
- Adding some comments to make the code more readable
- Removing unused code and imports.

I look forward to your feedback and further instructions.
Here are some greenshots you will need:
Screenshot 2024-11-02 083914
Screenshot 2024-11-02 084645
Screenshot 2024-11-02 085418

**Comment by hasin-zaman** [comment]
This is perfect! Great job! @Giang0402

**Comment by hasin-zaman** [comment]
@Giang0402 you haven't pushed your changes. Let me assign you another issue and you can push your changes there. Also, there is one more issue you need to address. So the component you have developed is an input text field and not a text which means it should be in the category of input fields. Just go to navlinks add another category "Input Fields", in reusable-components add another folder "input-fields" and make required changes to move from texts category to input fields category. Everything else is great. Thanks

**Comment by thgiang-coder** [comment]
**@hasin-zaman**  Thanks for your feedback, I will complete this task soon.

**Pull request merged**
