### PR TITLE
Added Sign Up form component

### PR DESCRIPTION
**Pull request by Ravi0529**
Create a reuseable sign up component, where user can change the number of inputs, placeholders, form title, sign up button texts and color, and can design the component as per their requirement!
Screenshot 2024-11-10 175600

### CODE REVIEW

**Review by hasin-zaman — CHANGES_REQUESTED** [review]
Good job @Ravi0529 ! Everything looks great. Kindly take the latest pull and of dev branch and resubmit it. Thanks.

**Comment by Ravi0529** [comment]
On it!

**Comment by Ravi0529** [comment]
I have updated the PR, is it done?

**Review by hasin-zaman — APPROVED** [review]

**Comment by hasin-zaman** [comment]
Yes @Ravi0529 Good job! I have merged your PR.

**Pull request merged**
